### PR TITLE
Add fzf layout option

### PR DESCRIPTION
**Pull request by kevintraver**
Add tmux variable to set fzf layout.

### CODE REVIEW

**Comment by kevintraver** [comment]
I wonder if this should be opt-in functionality, instead of setting a default?

Right now if someone has this set `FZF_DEFAULT_OPTS="--reverse"` this new default setting would override that and change the **tmux-fuzzback** behavior.

**Comment by kevintraver** [comment]
That being said... I do think `default` is a sensible layout in this context (since you are scrolling back up in history)

The *extrakto* plugin does that same thing:

https://github.com/laktak/extrakto/blob/9c0c0f3a26e2942b273c2c4d9ca67df4cc97bf55/scripts/helpers.sh#L89-L91

**Comment by roosta** [comment]
Hi Kevin, thanks for this!

I think `default` is a sensible default as well, and I don't mind including it as an option. If extracto does the same thing then all the better. Out of curiosity why would anyone want to change the layout when rendering the terminal like fuzzback does?

**Comment by kevintraver** [comment]
Good question. So I actually dont know why anyone would, but having the ability to just set the option is what I wanted.  I use `fzf` with the default as reverse `FZF_DEFAULT_OPTS="--reverse"`, but I want *tmux-fuzzback* to still use the default layout option.

**Comment by kevintraver** [comment]
Having this as an option now allows independent configuration of `fzf` and *tmux-fuzzback*, which is great!

**Comment by roosta** [comment]
That makes sense, glad to include this feature!

**Pull request merged**
