### PR TITLE
Adding fzf-colors option

### PR DESCRIPTION
**Pull request by hqkhan**
This will allow users to add colors to fzf's window using `fuzzback-fzf-colors` option.

### CODE REVIEW

**Comment by roosta** [comment]
The tests fail because the default value doesn't work, you can't pass an empty string as a color argument to fzf/sk. You need to figure out what fzf uses as default, and pass that as the default for `tmux_get`.

**Comment by roosta** [comment]
Also I worry that this option will override the defaults I've set with fzf. Didn't think of that initially but if we pass a default colorscheme fzf will this option ignore `FZF_DEFAULT_OPTS` and whatever colorscheme is set there?

**Comment by roosta** [comment]
A possible solution could be some branching, only setting the `--color` option if it has a value.

**Comment by hqkhan** [comment]
> The tests fail because the default value doesn't work, you can't pass an empty string as a color argument to fzf/sk. You need to figure out what fzf uses as default, and pass that as the default for `tmux_get`.

Ah ok. I tested it by not passting anything and it resorted to the default colorscheme fzf has. I will find out what this is.

**Comment by hqkhan** [comment]
> Also I worry that this option will override the defaults I've set with fzf. Didn't think of that initially but if we pass a default colorscheme fzf will this option ignore `FZF_DEFAULT_OPTS` and whatever colorscheme is set there?

Aren't we already ignoring `FZF_DEFAULT_OPTS`? I have a few opts set in that var but they were not respected in fuzzback.

**Comment by hqkhan** [comment]
> A possible solution could be some branching, only setting the `--color` option if it has a value.

Definitely! I'll make the change later today

**Comment by roosta** [comment]
> Aren't we already ignoring FZF_DEFAULT_OPTS? I have a few opts set in that var but they were not respected in fuzzback.

Hmm, you might be right there, might not be an issue, it seems to fall back to default opts if the option is set with the command. I tried `fzf --color="fg:13", and fzf changes the forground color, but the rest of the colors falls back to default opts it seems.

**Comment by hqkhan** [comment]
Sorry about being MIA. Been a busy week. We're looking to go away from empty string as default right? To let tests pass? Or do you think the branching is still necessary if `--color` is set?

**Comment by roosta** [comment]
No worries, thats life :) I think we can just add the default `dark`, seems that is the default for fzf. It will fall back to 16 colors if 256 isn't supported, and I suppose a user can set the `---color=16` if the dark is a problem.

So my suggestion is no branching, just pass `dark` as the default color value to `tmux_get`

**Pull request merged**
